/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.qualityagent.controller;import cn.zhuatech.qualityagent.common.ApiResponse;import cn.zhuatech.qualityagent.service.CapaRecommendationReleaseService;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                          */
@RestController @RequestMapping("/api/enterprise/qualityagent")public class CapaRecommendationReleaseController{private final CapaRecommendationReleaseService service;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                 */
public CapaRecommendationReleaseController(CapaRecommendationReleaseService service){this.service=service;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
@PostMapping("/capa-recommendation-release")public ApiResponse<CapaRecommendationReleaseService.Assessment>assess(@Valid @RequestBody CapaRecommendationReleaseService.Request request){return ApiResponse.ok(service.assess(request));}}
