/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.qualityagent.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                     */
class CapaRecommendationReleaseServiceTest{private final CapaRecommendationReleaseService s=new CapaRecommendationReleaseService();/**
                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                        */
@Test void releasesControlledCapa(){var r=s.assess(new CapaRecommendationReleaseService.Request("C1",true,true,true,true,true,true,true,true,true));assertThat(r.decision()).isEqualTo(CapaRecommendationReleaseService.Decision.RELEASE);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@Test void reviewsEffectivenessAndAudit(){var r=s.assess(new CapaRecommendationReleaseService.Request("C2",true,true,true,true,true,true,false,false,true));assertThat(r.actions()).hasSize(2);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
@Test void blocksWeakCapa(){var r=s.assess(new CapaRecommendationReleaseService.Request("C3",false,false,false,false,false,false,true,true,false));assertThat(r.blockers()).hasSize(7);}}
