/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.qualityagent.service;import jakarta.validation.constraints.*;import org.springframework.stereotype.Service;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service public class CapaRecommendationReleaseService{/**
                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                        */
public Assessment assess(Request r){List<String>b=new ArrayList<>(),a=new ArrayList<>();if(!r.nonconformanceLinked())b.add("CAPA 未关联原始不符合项");if(!r.containmentVerified())b.add("临时遏制措施未验证");if(!r.rootCauseEvidenceApproved())b.add("根因证据未批准");if(!r.actionOwnerAndDueDateAssigned())b.add("纠正预防措施缺少责任人与期限");if(!r.validationProtocolApproved())b.add("措施验证方案未批准");if(!r.regulatoryImpactReviewed())b.add("法规与客户影响未复核");if(!r.finalApprovalComplete())b.add("CAPA 建议发布审批未完成");if(!b.isEmpty()){a.add("阻断 CAPA 发布并完成质量与法规复核");return new Assessment(Decision.BLOCKED,b,a);}if(!r.effectivenessCheckPlanned()||!r.changeAuditEnabled()){if(!r.effectivenessCheckPlanned())a.add("制定有效性检查指标、样本和日期");if(!r.changeAuditEnabled())a.add("启用建议、人工修改和审批版本审计");return new Assessment(Decision.REVIEW,b,a);}a.add("批准 CAPA 发布并持续跟踪措施与有效性验证");return new Assessment(Decision.RELEASE,b,a);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
public record Request(@NotBlank String capaId,boolean nonconformanceLinked,boolean containmentVerified,boolean rootCauseEvidenceApproved,boolean actionOwnerAndDueDateAssigned,boolean validationProtocolApproved,boolean regulatoryImpactReviewed,boolean effectivenessCheckPlanned,boolean changeAuditEnabled,boolean finalApprovalComplete){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
public record Assessment(Decision decision,List<String>blockers,List<String>actions){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
public enum Decision{RELEASE,REVIEW,BLOCKED}}
